package cn.addenda.exactsqllog.proxy.jdbc;

import cn.addenda.exactsqllog.proxy.sql.EslStatementSqlAttachment;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * @author addenda
 * @since 2024/8/24 17:20
 */
public class EslStatement extends AbstractEslStatement<Statement, EslStatementSqlAttachment> {

  public EslStatement(Statement delegate, EslConnection eslConnection) {
    super(delegate, eslConnection);
    this.eslStatementSqlAttachment = new EslStatementSqlAttachment(getExecutionQueue(), getDataSourceEslId(), getConnectionEslId(), getEslId());
  }

  @Override
  public ResultSet executeQuery(String sql) throws SQLException {
    long start = curMills();
    ResultSet resultSet = delegate.executeQuery(sql);
    executeQuery(sql, start);
    return resultSet;
  }

  @Override
  public int executeUpdate(String sql) throws SQLException {
    long start = curMills();
    int r = delegate.executeUpdate(sql);
    executeUpdate(sql, start);
    return r;
  }

  @Override
  public void close() throws SQLException {
    delegate.close();
    closeEsl();
  }

  @Override
  public void closeEsl() {
    // execute的数据，已经写入executionQueue了，随着事务的执行会写出去。没有execute的数据会丢失。
    eslStatementSqlAttachment.clearBatch();
    getEslConnection().removeEslStatement(this);
  }

  @Override
  public boolean execute(String sql) throws SQLException {
    long start = curMills();
    boolean r = delegate.execute(sql);
    execute(sql, start);
    return r;
  }

  @Override
  public void addBatch(String sql) throws SQLException {
    delegate.addBatch(sql);
    eslStatementSqlAttachment.addBatchSql(sql);
  }

  @Override
  public void clearBatch() throws SQLException {
    delegate.clearBatch();
    eslStatementSqlAttachment.clearBatch();
  }

  @Override
  public int[] executeBatch() throws SQLException {
    long start = curMills();
    int[] r = delegate.executeBatch();
    executeBatchUpdate(start);
    return r;
  }

  @Override
  public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    long start = curMills();
    int r = delegate.executeUpdate(sql, autoGeneratedKeys);
    executeUpdate(sql, start);
    return r;
  }

  @Override
  public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
    long start = curMills();
    int r = delegate.executeUpdate(sql, columnIndexes);
    executeUpdate(sql, start);
    return r;
  }

  @Override
  public int executeUpdate(String sql, String[] columnNames) throws SQLException {
    long start = curMills();
    int r = delegate.executeUpdate(sql, columnNames);
    executeUpdate(sql, start);
    return r;
  }

  @Override
  public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
    long start = curMills();
    boolean r = delegate.execute(sql, autoGeneratedKeys);
    execute(sql, start);
    return r;
  }

  @Override
  public boolean execute(String sql, int[] columnIndexes) throws SQLException {
    long start = curMills();
    boolean r = delegate.execute(sql, columnIndexes);
    execute(sql, start);
    return r;
  }

  @Override
  public boolean execute(String sql, String[] columnNames) throws SQLException {
    long start = curMills();
    boolean r = delegate.execute(sql, columnNames);
    execute(sql, start);
    return r;
  }

  @Override
  public long[] executeLargeBatch() throws SQLException {
    long start = curMills();
    long[] r = delegate.executeLargeBatch();
    executeBatchUpdate(start);
    return r;
  }

  @Override
  public long executeLargeUpdate(String sql) throws SQLException {
    long start = curMills();
    long r = delegate.executeLargeUpdate(sql);
    executeUpdate(sql, start);
    return r;
  }

  @Override
  public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    long start = curMills();
    long r = delegate.executeLargeUpdate(sql, autoGeneratedKeys);
    executeUpdate(sql, start);
    return r;
  }

  @Override
  public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
    long start = curMills();
    long r = delegate.executeLargeUpdate(sql, columnIndexes);
    executeUpdate(sql, start);
    return r;
  }

  @Override
  public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
    long start = curMills();
    long r = delegate.executeLargeUpdate(sql, columnNames);
    executeUpdate(sql, start);
    return r;
  }

}
